project_id = "nsakwffvlgrlxcyozoft"

[functions.seed-trips]
verify_jwt = false

[functions.seed-surveys]
verify_jwt = false

[functions.link-trips-to-incentives]
verify_jwt = false

[functions.seed-q4-trips]
verify_jwt = false
